export default {
  Button: jest.fn().mockImplementation(() => ({
    connect: jest.fn(),
    disconnect: jest.fn(),
    set_style: jest.fn(),
    get_style: jest.fn(),
    add_child: jest.fn(),
    remove_child: jest.fn(),
    show: jest.fn(),
    hide: jest.fn(),
    destroy: jest.fn(),
    grab_key_focus: jest.fn(),
    set_reactive: jest.fn(),
  })),
  Label: jest.fn().mockImplementation(() => ({
    set_text: jest.fn(),
    get_text: jest.fn(),
    connect: jest.fn(),
    disconnect: jest.fn(),
    set_style: jest.fn(),
    show: jest.fn(),
    hide: jest.fn(),
    destroy: jest.fn(),
  })),
  BoxLayout: jest.fn().mockImplementation(() => ({
    add_child: jest.fn(),
    remove_child: jest.fn(),
    connect: jest.fn(),
    disconnect: jest.fn(),
    set_style: jest.fn(),
    show: jest.fn(),
    hide: jest.fn(),
    destroy: jest.fn(),
    get_size: jest.fn(() => [100, 100]),
    get_position: jest.fn(() => [0, 0]),
    set_size: jest.fn(),
    set_position: jest.fn(),
  })),
  Widget: jest.fn().mockImplementation(() => ({
    add_child: jest.fn(),
    remove_child: jest.fn(),
    connect: jest.fn(),
    disconnect: jest.fn(),
    set_style: jest.fn(),
    show: jest.fn(),
    hide: jest.fn(),
    destroy: jest.fn(),
    get_parent: jest.fn(),
    grab_key_focus: jest.fn(),
  })),
  Icon: jest.fn(),
  Entry: jest.fn(),
  ScrollView: jest.fn(),
};