name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install JavaScript dependencies
      run: npm install
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Run JavaScript tests
      run: npm run test:js
    
    - name: Run integration tests
      run: npm run test:integration
    
    - name: Generate coverage report
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info

  python-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg xdotool xclip
    
    - name: Install Python dependencies
      run: |
        pip install pytest pytest-cov pytest-mock
        pip install -r requirements.txt
    
    - name: Run Python tests
      run: |
        cd src
        python -m pytest ../tests/python --cov=. --cov-report=xml
    
    - name: Upload Python coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./src/coverage.xml

  extension-validation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install GNOME Shell development tools
      run: |
        sudo apt-get update
        sudo apt-get install -y gnome-shell-extensions gettext
    
    - name: Validate extension metadata
      run: |
        cd src
        # Check metadata.json is valid JSON
        python3 -m json.tool metadata.json > /dev/null
        # Check required fields
        grep -q '"uuid"' metadata.json
        grep -q '"name"' metadata.json
        grep -q '"shell-version"' metadata.json
    
    - name: Validate GSettings schema
      run: |
        cd src/schemas
        # Compile schema to check for syntax errors
        glib-compile-schemas .
    
    - name: Check extension structure
      run: |
        # Verify required files exist
        test -f src/js/extension.js || test -f src/extension.ts
        test -f src/metadata.json
        test -f src/whisper_typing.py
        test -d src/js/lib
        test -d src/schemas
        test -d src/icons